base_100 = "#F9F9F7"
base_200 = "#F0EFEA"
base_300 = "#EAE9E3"
base_content = "#3A2C52"
primary = "#6BEAD8"
primary_content = "#1F6F67"
secondary = "#FAD6E6"
secondary_content = "#8A2C25"
accent = "#FAF4D5"
accent_content = "#7C6A2A"
neutral = "#434344"
neutral_content = "#EBEBEB"
info = "#4FA7FF"
info_content = "#0F375A"
success = "#4AD97E"
success_content = "#123C25"
warning = "#FFD866"
warning_content = "#3E3025"
error = "#E24A3C"
error_content = "#5C1212"
radius_selector = "0.5"
radius_field = "0.25"
radius_box = "0.5"
size_selector = "0.25"
size_field = "0.25"
