base_100 = "#3A3C52"
base_200 = "#333545"
base_300 = "#2F313F"
base_content = "#C7D3E0"
primary = "#6EE7B7"
primary_content = "#1D2B24"
secondary = "#F4C38C"
secondary_content = "#2C1F14"
accent = "#C792EA"
accent_content = "#23152A"
neutral = "#2C2E3D"
neutral_content = "#C7D3E0"
info = "#7DD3FC"
info_content = "#14232C"
success = "#6EE7B7"
success_content = "#132922"
warning = "#FDE68A"
warning_content = "#292614"
error = "#FCA5A5"
error_content = "#291616"
radius_selector = "1.0"
radius_field = "0.5"
radius_box = "1.0"
size_selector = "0.25"
size_field = "0.25"
