base_100 = "#2B2A3E"
base_200 = "#262638"
base_300 = "#222232"
base_content = "#F9F9F6"
primary = "#FF79C6"
primary_content = "#2A0E1D"
secondary = "#BD93F9"
secondary_content = "#1F142E"
accent = "#50FA7B"
accent_content = "#182217"
neutral = "#44475A"
neutral_content = "#E6E6EB"
info = "#8BE9FD"
info_content = "#16262B"
success = "#50FA7B"
success_content = "#16291C"
warning = "#F1FA8C"
warning_content = "#292B16"
error = "#FF5555"
error_content = "#260D0D"
radius_selector = "0.5"
radius_field = "0.25"
radius_box = "0.5"
size_selector = "0.25"
size_field = "0.25"
