base_100 = "#34312F"
base_200 = "#2E2B29"
base_300 = "#272523"
base_content = "#D4D2D0"
primary = "#32A861"
primary_content = "#000000"
secondary = "#3BB07F"
secondary_content = "#232F28"
accent = "#44A9A0"
accent_content = "#24312F"
neutral = "#455951"
neutral_content = "#DADFDB"
info = "#3F77DB"
info_content = "#000000"
success = "#3CA86A"
success_content = "#000000"
warning = "#EBCB3B"
warning_content = "#000000"
error = "#D8462D"
error_content = "#000000"
radius_selector = "0.5"
radius_field = "0.25"
radius_box = "0.5"
size_selector = "0.25"
size_field = "0.25"
