base_100 = "#ECEBE9"
base_200 = "#D9D7D5"
base_300 = "#C7C5C3"
base_content = "#2B2A29"
primary = "#B3362D"
primary_content = "#FFFFFF"
secondary = "#913F4A"
secondary_content = "#E7D6D9"
accent = "#5C8C6D"
accent_content = "#FFFFFF"
neutral = "#3C463D"
neutral_content = "#ECEBE9"
info = "#3F77DB"
info_content = "#000000"
success = "#3CA86A"
success_content = "#000000"
warning = "#EBCB3B"
warning_content = "#000000"
error = "#D8462D"
error_content = "#000000"
radius_selector = "0.5"
radius_field = "0.25"
radius_box = "0.5"
size_selector = "0.25"
size_field = "0.25"
