base_100 = "#2F2F2C"
base_200 = "#1D1C1B"
base_300 = "#000000"
base_content = "#D8D8D8"
primary = "#FF9E2C"
primary_content = "#272929"
secondary = "#9D3FFF"
secondary_content = "#E9DAFF"
accent = "#4FD273"
accent_content = "#000000"
neutral = "#3C352D"
neutral_content = "#D7D2CA"
info = "#5D72FF"
info_content = "#E7EAFF"
success = "#47D17C"
success_content = "#15281D"
warning = "#E5B93F"
warning_content = "#2C2414"
error = "#D64A2A"
error_content = "#2B120D"
radius_selector = "0.5"
radius_field = "0.25"
radius_box = "0.5"
size_selector = "0.25"
size_field = "0.25"
