base_100 = "#FFFFFF"
base_200 = "#FAFAFA"
base_300 = "#F2F2F2"
base_content = "#353535"
primary = "#5B3DFF"
primary_content = "#F1EEFF"
secondary = "#FF4770"
secondary_content = "#FFF0F6"
accent = "#3DDBB8"
accent_content = "#125F52"
neutral = "#222222"
neutral_content = "#EBEBEB"
info = "#3FA3FF"
info_content = "#0F375A"
success = "#3DDB63"
success_content = "#185B2A"
warning = "#FFD94D"
warning_content = "#664700"
error = "#FF4B4B"
error_content = "#5C1212"
radius_selector = "0.5"
radius_field = "0.25"
radius_box = "0.5"
size_selector = "0.25"
size_field = "0.25"
