base_100 = "#221F24"
base_200 = "#322E34"
base_300 = "#3B373E"
base_content = "#E2E66B"
primary = "#FFFFFF"
primary_content = "#333333"
secondary = "#3B3F66"
secondary_content = "#D9DAF0"
accent = "#5C3C55"
accent_content = "#E0D6DE"
neutral = "#3E3B2F"
neutral_content = "#F4F6E0"
info = "#799FFF"
info_content = "#242A3F"
success = "#60E493"
success_content = "#1C2E1D"
warning = "#FFE680"
warning_content = "#2A2914"
error = "#E05C42"
error_content = "#26120E"
radius_selector = "0.5"
radius_field = "0.25"
radius_box = "0.5"
size_selector = "0.25"
size_field = "0.25"
