base_100 = "#FFFFFF"
base_200 = "#F7F7F7"
base_300 = "#F0F0F0"
base_content = "#333333"
primary = "#DEDEDE"
primary_content = "#434343"
secondary = "#DEDEDE"
secondary_content = "#434343"
accent = "#DEDEDE"
accent_content = "#434343"
neutral = "#DEDEDE"
neutral_content = "#434343"
info = "#2B53A3"
info_content = "#D9E3FB"
success = "#246D4A"
success_content = "#D9F7E7"
warning = "#A1741E"
warning_content = "#FFF3C4"
error = "#A6321D"
error_content = "#F2C8B7"
radius_selector = "0.5"
radius_field = "0.25"
radius_box = "0.5"
size_selector = "0.25"
size_field = "0.25"
