#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Nationality {
	Afghan,
	Armenian,
	Azerbaijani,
	Bahraini,
	Bangladeshi,
	Bhutanese,
	Bruneian,
	Burmese,
	Cambodian,
	Chinese,
	Cypriot,
	Georgian,
	Indian,
	Indonesian,
	Iranian,
	Iraqi,
	Israeli,
	Japanese,
	Jordanian,
	Kazakh,
	Kuwaiti,
	Kyrgyz,
	Laotian,
	Lebanese,
	Malaysian,
	Maldivian,
	Mongolian,
	Nepalese,
	NorthKorean,
	Omani,
	Pakistani,
	Palestinian,
	#[default]
	Filipino,
	Qatari,
	Saudi,
	Singaporean,
	SouthKorean,
	SriLankan,
	Syrian,
	Taiwanese,
	Tajik,
	Thai,
	Timorese,
	Turkish,
	Turkmen,
	Emirati,
	Uzbek,
	Vietnamese,
	Yemeni,
}

impl std::fmt::Display for Nationality {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		let name = match self {
			Self::Afghan => "Afghan",
			Self::Armenian => "Armenian",
			Self::Azerbaijani => "Azerbaijani",
			Self::Bahraini => "Bahraini",
			Self::Bangladeshi => "Bangladeshi",
			Self::Bhutanese => "Bhutanese",
			Self::Bruneian => "Bruneian",
			Self::Burmese => "Burmese",
			Self::Cambodian => "Cambodian",
			Self::Chinese => "Chinese",
			Self::Cypriot => "Cypriot",
			Self::Georgian => "Georgian",
			Self::Indian => "Indian",
			Self::Indonesian => "Indonesian",
			Self::Iranian => "Iranian",
			Self::Iraqi => "Iraqi",
			Self::Israeli => "Israeli",
			Self::Japanese => "Japanese",
			Self::Jordanian => "Jordanian",
			Self::Kazakh => "Kazakh",
			Self::Kuwaiti => "Kuwaiti",
			Self::Kyrgyz => "Kyrgyz",
			Self::Laotian => "Laotian",
			Self::Lebanese => "Lebanese",
			Self::Malaysian => "Malaysian",
			Self::Maldivian => "Maldivian",
			Self::Mongolian => "Mongolian",
			Self::Nepalese => "Nepalese",
			Self::NorthKorean => "North Korean",
			Self::Omani => "Omani",
			Self::Pakistani => "Pakistani",
			Self::Palestinian => "Palestinian",
			Self::Filipino => "Filipino",
			Self::Qatari => "Qatari",
			Self::Saudi => "Saudi",
			Self::Singaporean => "Singaporean",
			Self::SouthKorean => "South Korean",
			Self::SriLankan => "Sri Lankan",
			Self::Syrian => "Syrian",
			Self::Taiwanese => "Taiwanese",
			Self::Tajik => "Tajik",
			Self::Thai => "Thai",
			Self::Timorese => "Timorese",
			Self::Turkish => "Turkish",
			Self::Turkmen => "Turkmen",
			Self::Emirati => "Emirati",
			Self::Uzbek => "Uzbek",
			Self::Vietnamese => "Vietnamese",
			Self::Yemeni => "Yemeni",
		};
		write!(f, "{name}")
	}
}
