use iced::widget::Text;

use crate::gui::styles::{
	style_constant::fonts::ICONS, types::style_type::StyleType
};

#[allow(clippy::large_enum_variant, unused)]
#[derive(Debug, Clone)]
pub enum Icon {
	AlignJustify,
	ChartPieSlice,
	ChartPie,
	CalendarDays,
	BookText,
	BellRing,
	Bell,
	ArrowUpNarrowWide,
	ArrowDownWideNarrow,
	ArrowBendDoubleUpRight,
	SaveAll,
	Package,
	Palette,
	Paperclip,
	PhPeso,
	Phone,
	Plus,
	Power,
	Printer,
	ReceiptText,
	RotateCcw,
	Save,
	Send,
	Settings,
	SlidersHorizontal,
	SlidersVertical,
	SpeakerSimpleHigh,
	SpeakerSimpleLow,
	SpeakerSimpleNone,
	SpeakerSimpleX,
	Trash2,
	TrendingDown,
	TrendingUp,
	UploadSimple,
	UserRoundMinus,
	UserRoundPen,
	UserRoundPlus,
	UsersRound,
	UserRound,
	Venus,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Eye,
	EyeOff,
	FileText,
	FolderClosed,
	FolderOpen,
	Funnel,
	Globe,
	House,
	IdCard,
	Languages,
	LayoutPanelLeft,
	LockKeyhole,
	LockKeyholeOpen,
	LogOut,
	Mail,
	Map,
	MapPin,
	Mars,
	MessageSquareMore,
	Morphiq,
	Newspaper,
	NotebookText,
	UserRoundSearch,
	Archive,
	Search,
	Ban,
	CircleUserRound,
	MailOpen,
	CloseX,
	ArrowUpFromLine,
	Sun,
	Moon,
	CreditCard,
	Layers,
	ShoppingCart,
	ViewGrid,
	Repeat,
	Sync,
	Check,
	Coins,
	HandCoins,
	CalendarClock,
	Calendar,
	Flag,
	Information,
	CloudUpload,
}

impl Icon {
	#[allow(clippy::use_self)]
	pub const fn codepoint(&self) -> char {
		match self {
			Icon::AlignJustify => '0',
			Icon::ChartPieSlice => '1',
			Icon::ChartPie => '2',
			Icon::CalendarDays => '3',
			Icon::BookText => '4',
			Icon::BellRing => '5',
			Icon::Bell => '6',
			Icon::ArrowUpNarrowWide => '7',
			Icon::ArrowDownWideNarrow => '8',
			Icon::ArrowBendDoubleUpRight => '9',
			Icon::SaveAll => ':',
			Icon::Package => ';',
			Icon::Palette => '<',
			Icon::Paperclip => '=',
			Icon::PhPeso => '>',
			Icon::Phone => '?',
			Icon::Plus => '@',
			Icon::Power => 'A',
			Icon::Printer => 'B',
			Icon::ReceiptText => 'C',
			Icon::RotateCcw => 'D',
			Icon::Save => 'E',
			Icon::Send => 'F',
			Icon::Settings => 'G',
			Icon::SlidersHorizontal => 'H',
			Icon::SlidersVertical => 'I',
			Icon::SpeakerSimpleHigh => 'J',
			Icon::SpeakerSimpleLow => 'K',
			Icon::SpeakerSimpleNone => 'L',
			Icon::SpeakerSimpleX => 'M',
			Icon::Trash2 => 'N',
			Icon::TrendingDown => 'O',
			Icon::TrendingUp => 'P',
			Icon::UploadSimple => 'Q',
			Icon::UserRoundMinus => 'R',
			Icon::UserRoundPen => 'S',
			Icon::UserRoundPlus => 'T',
			Icon::UsersRound => 'U',
			Icon::Venus => 'V',
			Icon::ChevronDown => 'W',
			Icon::ChevronLeft => 'X',
			Icon::ChevronRight => 'Y',
			Icon::ChevronUp => 'Z',
			Icon::Eye => '[',
			Icon::EyeOff => '\\',
			Icon::FileText => ']',
			Icon::FolderClosed => '^',
			Icon::FolderOpen => '_',
			Icon::Funnel => '`',
			Icon::Globe => 'a',
			Icon::House => 'b',
			Icon::IdCard => 'c',
			Icon::Languages => 'd',
			Icon::LayoutPanelLeft => 'e',
			Icon::LockKeyhole => 'f',
			Icon::LockKeyholeOpen => 'g',
			Icon::LogOut => 'h',
			Icon::Mail => 'i',
			Icon::Map => 'j',
			Icon::MapPin => 'k',
			Icon::Mars => 'l',
			Icon::MessageSquareMore => 'm',
			Icon::Morphiq => 'n',
			Icon::Newspaper => 'o',
			Icon::NotebookText => 'p',
			Icon::UserRoundSearch => 'q',
			Icon::Archive => 'r',
			Icon::Search => 's',
			Icon::Ban => 't',
			Icon::CircleUserRound => 'u',
			Icon::MailOpen => 'v',
			Icon::CloseX => 'w',
			Icon::ArrowUpFromLine => 'x',
			Icon::UserRound => 'y',
			Icon::Sun => 'z',
			Icon::Moon => '{',
			Icon::CreditCard => '|',
			Icon::Layers => '}',
			Icon::ShoppingCart => '~',
			Icon::ViewGrid => '!',
			Icon::Repeat => '"',
			Icon::Sync => '#',
			Icon::Check => '$',
			Icon::Coins => '%',
			Icon::HandCoins => '&',
			Icon::CalendarClock => '\'',
			Icon::Flag => '(',
			Icon::Information => ')',
			Icon::CloudUpload => '*',
			Icon::Calendar => '+',
		}
	}

	pub fn to_text<'a>(&self) -> Text<'a, StyleType> {
		Text::new(self.codepoint().to_string()).font(ICONS)
	}
}
